# Generated by Django 5.2.6 on 2025-10-09 05:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('barangay_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Barangays',
            },
        ),
        migrations.CreateModel(
            name='LogHistory',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('log_title', models.CharField(choices=[('LOGIN', 'Account Login'), ('REGISTER', 'Account Registration'), ('MODIFY', 'Account Modification'), ('DELETE', 'Account Deletion'), ('PREDICTION', 'Prediction Made'), ('DATA_ENTRY', 'Data Entry'), ('SYSTEM', 'System Event')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Log History',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Account Manager',
            },
        ),
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False)),
                ('admin_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Admin Data',
            },
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('rainfall_chance', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('is_day', models.BooleanField()),
                ('wind_speed_10m', models.FloatField()),
                ('weather_code', models.FloatField()),
                ('time', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'time'], name='backend_cur_locatio_484b53_idx')],
                'unique_together': {('location', 'time')},
            },
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('rainfall_chance_max', models.FloatField()),
                ('temperature_2m_max', models.FloatField(blank=True, null=True)),
                ('temperature_2m_min', models.FloatField()),
                ('wind_speed_10m_max', models.FloatField()),
                ('weather_code', models.FloatField()),
                ('avg_humidity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'date'], name='backend_dai_locatio_a9d40d_idx')],
                'unique_together': {('location', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DengueCase',
            fields=[
                ('dengue_case_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_reported', models.PositiveIntegerField()),
                ('week_reported', models.PositiveIntegerField()),
                ('num_cases', models.PositiveIntegerField()),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.barangay')),
            ],
            options={
                'verbose_name_plural': 'Dengue Cases',
            },
        ),
        migrations.CreateModel(
            name='HistoricalWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, default='Malabon', max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('weather_code', models.FloatField()),
                ('temperature_2m_max', models.FloatField()),
                ('temperature_2m_min', models.FloatField()),
                ('wind_speed_10m_max', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Historical Weather Data',
                'indexes': [models.Index(fields=['location', 'date'], name='backend_his_locatio_401090_idx')],
                'unique_together': {('location', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateTimeField(db_index=True)),
                ('temperature_2m', models.FloatField()),
                ('rainfall_chance', models.FloatField()),
                ('wind_speed_10m', models.FloatField()),
                ('relative_humidity_2m', models.FloatField()),
                ('is_day', models.BooleanField()),
                ('weather_code', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'date'], name='backend_hou_locatio_613843_idx')],
                'unique_together': {('location', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.barangay')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Data',
            },
        ),
        migrations.CreateModel(
            name='WeeklyAverage',
            fields=[
                ('weekly_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(default='Malabon', max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('avg_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_rainfall_chance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_rainy_days', models.PositiveIntegerField(default=0)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Weekly Averages',
                'ordering': ['-year', '-week'],
                'unique_together': {('location', 'year', 'week')},
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('prediction_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_prediction', models.PositiveIntegerField()),
                ('week_prediction', models.PositiveIntegerField()),
                ('numerical_risk_level', models.PositiveIntegerField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('risk_level', models.CharField(max_length=20)),
                ('trend', models.CharField(default='neutral', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.barangay')),
            ],
            options={
                'verbose_name_plural': 'Prediction Results',
                'unique_together': {('barangay', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('weather_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_recorded', models.DateField()),
                ('time_recorded', models.TimeField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=6)),
                ('windspeed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_source', models.CharField(choices=[('PAGASA', 'Philippine Atmospheric, Geophysical and Astronomical Services Administration'), ('LOCAL', 'Local Weather Station'), ('OTHER', 'Other Source')], max_length=10)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.barangay')),
            ],
            options={
                'verbose_name_plural': 'Weather Data',
                'unique_together': {('barangay', 'date_recorded', 'time_recorded')},
            },
        ),
    ]
