# Generated by Django 5.2.5 on 2025-09-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denguecase',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
