# Generated by Django 5.2.5 on 2025-09-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_denguecase_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loghistory',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
