# Generated by Django 5.2.5 on 2025-09-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_loghistory_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogHistory',
        ),
    ]
