# Generated by Django 5.2.5 on 2025-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_delete_loghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogHistory',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('log_title', models.CharField(choices=[('LOGIN', 'Account Login'), ('REGISTER', 'Account Registration'), ('PREDICTION', 'Prediction Made'), ('DATA_ENTRY', 'Data Entry'), ('SYSTEM', 'System Event')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Log History',
            },
        ),
    ]
