# Generated by Django 5.2.5 on 2025-09-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_loghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loghistory',
            name='log_title',
            field=models.CharField(choices=[('LOGIN', 'Account Login'), ('REGISTER', 'Account Registration'), ('MODIFY', 'Account Modification'), ('PREDICTION', 'Prediction Made'), ('DATA_ENTRY', 'Data Entry'), ('SYSTEM', 'System Event')], max_length=20),
        ),
    ]
