# Generated by Django 5.2.5 on 2025-09-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_loghistory_log_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictionResult',
        ),
    ]
