# Generated by Django 5.2.5 on 2025-09-26 08:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_delete_predictionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('prediction_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_prediction', models.PositiveIntegerField()),
                ('week_prediction', models.PositiveIntegerField()),
                ('numerical_risk_level', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('risk_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.barangay')),
            ],
            options={
                'verbose_name_plural': 'Prediction Results',
                'unique_together': {('barangay_id', 'created_at')},
            },
        ),
    ]
