# Generated by Django 5.2.5 on 2025-09-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_predictionresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionresult',
            old_name='barangay_id',
            new_name='barangay',
        ),
        migrations.AlterUniqueTogether(
            name='predictionresult',
            unique_together={('barangay', 'created_at')},
        ),
    ]
