# Generated by Django 5.2.5 on 2025-09-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_barangay_id_predictionresult_barangay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, default='Malabon', max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('weather_code', models.FloatField()),
                ('temperature_2m_max', models.FloatField()),
                ('temperature_2m_min', models.FloatField()),
                ('wind_speed_10m_max', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Historical Weather Data',
                'indexes': [models.Index(fields=['location', 'date'], name='backend_his_locatio_401090_idx')],
                'unique_together': {('location', 'date')},
            },
        ),
    ]
