# Generated by Django 5.2.5 on 2025-09-30 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_historicalweather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='numerical_risk_level',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High'), (4, 'Very High')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
