# Generated by Django 5.2.5 on 2025-10-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_predictionresult_numerical_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='numerical_risk_level',
            field=models.PositiveIntegerField(),
        ),
    ]
