# Generated by Django 5.2.5 on 2025-10-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_predictionresult_numerical_risk_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='denguecase',
            unique_together=set(),
        ),
    ]
