# Generated by Django 5.2.5 on 2025-10-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denguecase',
            name='risk_level',
        ),
    ]
