# Generated by Django 5.2.5 on 2025-10-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_denguecase_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyforecast',
            name='avg_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
