# Generated by Django 5.2.5 on 2025-10-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_dailyforecast_avg_humidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyforecast',
            name='temperature_2m_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
