# Generated by Django 5.2.5 on 2025-10-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_dailyforecast_temperature_2m_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAverage',
            fields=[
                ('weekly_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(default='Malabon', max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('avg_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_rainfall_chance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_rainy_days', models.PositiveIntegerField(default=0)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Weekly Averages',
                'ordering': ['-year', '-week'],
                'unique_together': {('location', 'year', 'week')},
            },
        ),
    ]
