# Generated by Django 5.2.5 on 2025-10-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_weeklyaverage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='predictionresult',
            unique_together={('barangay', 'year_prediction', 'week_prediction')},
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='trend',
            field=models.CharField(default='neutral', max_length=10),
        ),
    ]
