# Generated by Django 5.2.5 on 2025-10-15 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_predictionresult_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('model_version_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('training_data_up_to', models.DateField()),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('total_training_samples', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.barangay')),
            ],
            options={
                'verbose_name_plural': 'Model Versions',
                'unique_together': {('barangay', 'version')},
            },
        ),
    ]
