# Generated by Django 5.2.5 on 2025-10-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
