# Generated by Django 5.2.5 on 2025-10-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_otp_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='code',
            new_name='otp_code',
        ),
    ]
